# This config uses the `.circleci/extended/orb-test.yml` as its base, and then publishes the app to S3.
# The workflow contained here demonstrates a practical application of `post-steps`
# and using workspace persistence
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0

jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    resource_class: small
    steps:
      - checkout
      # We need to build using vite. For now, we just us the static files.
      - run: echo "npm run build"
      - aws-s3/copy:
          from: dist/
          to: s3://leesjensen.com/public/
          arguments: --recursive
