# This config uses the `.circleci/extended/orb-test.yml` as its base, and then publishes the app to S3.
# The workflow contained here demonstrates a practical application of `post-steps`
# and using workspace persistence
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0

jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    resource_class: small
    steps:
      - checkout
      # At some point this needs to be changed to generate the entire /dist directory. Then we will no longer check it in.
      - run: cp src/index.html dist/index.html
      - aws-s3/copy:
          from: dist/
          to: s3://leesjensen.com/public/
          arguments: --recursive